name: fa
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.17
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - attrs==25.3.0
      - bddl==3.6.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chex==0.1.6
      - click==8.3.0
      - cloudpickle==2.1.0
      - cycler==0.12.1
      - decorator==4.4.2
      - deepspeed==0.16.6
      - diffusers==0.35.2
      - distrax==0.1.2
      - dlimp==0.0.1
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - draccus==0.8.0
      - dropout-layer-norm==0.1
      - easydict==1.9
      - egl-probe==1.0.2
      - einops==0.4.1
      - etils==1.13.0
      - evdev==1.9.2
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flash-attn==2.7.4.post1
      - flatbuffers==25.9.23
      - flax==0.7.0
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - funcsigs==1.0.2
      - fused-dense-lib==0.0.0
      - future==0.18.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.74.0
      - gym==0.25.2
      - gym-notices==0.1.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.2.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json-numpy==2.1.1
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupytext==1.17.3
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - libero==0.1.0
      - llvmlite==0.45.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-collections==1.1.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mujoco==3.3.6
      - nbformat==5.10.4
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - openexr==3.4.0
      - opt-einsum==3.4.0
      - optax==0.1.5
      - orbax==0.1.9
      - orbax-checkpoint==0.5.16
      - pathtools==0.1.2
      - peft==0.17.1
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - proglog==0.1.12
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pytest==8.4.2
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - robosuite==1.4.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.13.1
      - sentry-sdk==2.39.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.13.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow-addons==0.23.0
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tf-keras==2.15.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.57.1
      - trimesh==4.8.3
      - triton==3.1.0
      - typeguard==2.13.3
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - wandb==0.13.1
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: /home/tako/anaconda3/envs/fa
